databaseChangeLog:
  - changeSet:
      id: recreate-indexes-l4
      author: developer
      changes:
        # Drop old L4 indexes (with planId)
        - dropIndex:
            collectionName: lvl4CostDetailsOutlook
            keys: '{ "proposalId": 1, "planId": 1, "scenario": 1 }'
        - dropIndex:
            collectionName: lvl4CostDetailsLive
            keys: '{ "proposalId": 1, "planId": 1, "scenario": 1 }'
        - dropIndex:
            collectionName: lvl4CostDetailsBudget
            keys: '{ "proposalId": 1, "planId": 1, "scenario": 1 }'

        # Create new L4 indexes (without planId)
        - createIndex:
            collectionName: lvl4CostDetailsOutlook
            keys: '{ "proposalId": 1, "scenario": 1 }'
            options: '{ "unique": true, "name": "idx_l4cd_outlook_prpid_scnr_unq" }'
        - createIndex:
            collectionName: lvl4CostDetailsLive
            keys: '{ "proposalId": 1, "scenario": 1 }'
            options: '{ "unique": true, "name": "idx_l4cd_live_prpid_scnr_unq" }'
        - createIndex:
            collectionName: lvl4CostDetailsBudget
            keys: '{ "proposalId": 1, "scenario": 1 }'
            options: '{ "unique": true, "name": "idx_l4cd_budget_prpid_scnr_unq" }'

  - changeSet:
      id: recreate-indexes-l3
      author: developer
      changes:
        # Drop old L3 indexes (with planId)
        - dropIndex:
            collectionName: lvl3CostDetailsOutlook
            keys: '{ "proposalId": 1, "planId": 1, "scenario": 1, "year": 1 }'
        - dropIndex:
            collectionName: lvl3CostDetailsLive
            keys: '{ "proposalId": 1, "planId": 1, "scenario": 1, "year": 1 }'
        - dropIndex:
            collectionName: lvl3CostDetailsBudget
            keys: '{ "proposalId": 1, "planId": 1, "scenario": 1, "year": 1 }'

        # Create new L3 indexes (without planId)
        - createIndex:
            collectionName: lvl3CostDetailsOutlook
            keys: '{ "proposalId": 1, "scenario": 1, "year": 1 }'
            options: '{ "unique": true, "name": "idx_l3cd_outlook_prpid_scnr_year_unq" }'
        - createIndex:
            collectionName: lvl3CostDetailsLive
            keys: '{ "proposalId": 1, "scenario": 1, "year": 1 }'
            options: '{ "unique": true, "name": "idx_l3cd_live_prpid_scnr_year_unq" }'
        - createIndex:
            collectionName: lvl3CostDetailsBudget
            keys: '{ "proposalId": 1, "scenario": 1, "year": 1 }'
            options: '{ "unique": true, "name": "idx_l3cd_budget_prpid_scnr_year_unq" }'
